# gpu + tensorflow ver
FROM prireg:5000/rstudio-gpu-base:loca-1.0

ARG repo_host
RUN rm -rf /etc/apt/sources.list.d/*
COPY files/sources.list /etc/apt/sources.list
COPY files/pip.conf /etc/pip.conf
COPY files/Rprofile.site /etc/R/Rprofile.site
COPY files/Rprofile.site /usr/local/lib/R/etc/

# install java 1.8
RUN apt-get update && \
    apt-get --assume-yes install openjdk-8-jdk

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
    TZ=Asia/Seoul

RUN apt install -y curl libssl-dev libcurl4-openssl-dev libxml2-dev libv8-dev libbz2-dev libpcre2-dev liblzma-dev tzdata &&\
  Rscript -e "install.packages(c('jsonlite', 'RCurl'))" &&\
  Rscript -e "install.packages('stringi', configure.vars='ICUDT_DIR=~')" &&\
  Rscript -e "install.packages(c('openxlsx', 'dplyr', 'tidyr', 'ggplot2',\
  'readxl', 'magrittr', 'treemap', 'plotly', 'data.table',\
  'zoo', 'rpart', 'rattle', 'lime', 'shiny', \
  'randomForest', 'reshape2', 'reshape', 'gbm', 'R6'))"
  # 'xgboost'는 gpu버전 직접 빌드이므로 제외


# ----------sparklyR----------
# for add JAVA_HOME config
# rsparkling은 CRAN버전은 유지보수 안되므로 직접 레포에서 설치
# install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-3.0/3.32.0.3-1-3.0/R")
RUN R CMD javareconf &&\
    Rscript -e "install.packages(c('sparklyr', 'DBI', 'RJDBC'))"


# ----------h2o----------
COPY files/h2o-3.32.0.3.zip /usr/local/h2o-3.32.0.3.zip
RUN  unzip /usr/local/h2o-3.32.0.3.zip -d /usr/local &&\
  R CMD INSTALL /usr/local/h2o-3.32.0.3/R/h2o_3.32.0.3.tar.gz &&\
  rm /usr/local/h2o-3.32.0.3.zip &&\
  rm -rf h2o-3.32.0.3

# ----------xgb----------
# install.packages(c('data.table', 'magrittr', 'stringi', 'jsonlite'))
COPY files/xgboost_1.3.3.tar.gz /usr/local
RUN cd /usr/local &&\
    tar -zxvf xgboost_1.3.3.tar.gz &&\
    cd xgboost &&\
    mkdir build &&\
    cd build &&\
    cmake .. -DUSE_CUDA=ON -DR_LIB=ON &&\
    make install -j$(nproc) &&\
    cd /usr/local &&\
    rm -r xgboost

# ----------h2o4gpu(개발단계 코드 미성숙으로 미포함)----------
# https://github.com/h2oai/h2o4gpu
ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:$CUDA_HOME/extras/CUPTI/lib64
# r-reticulate virtualenv사용하지 않고 시스템 파이썬 사용 (tensorflow, h2ogpu 에서 필요)
# https://rstudio.github.io/reticulate/articles/versions.html
ENV RETICULATE_PYTHON=/usr/local/bin/python
# tensorflow, h2ogpu 사용을 위해 libstdc++ 업데이트
COPY files/libstdc++.so.6.0.27 /usr/lib/x86_64-linux-gnu
RUN cd /usr/lib/x86_64-linux-gnu &&\
    rm libstdc++.so.6 &&\
    ln -s libstdc++.so.6.0.27 libstdc++.so.6
RUN apt-get install --assume-yes libopenblas-dev pbzip2 &&\
    Rscript -e "install.packages(c('reticulate'))"
#     pip install h2o4gpu
# COPY files/h2o4gpu_rel-0.4.0.tag.gz /usr/local
# RUN cd /usr/local &&\
#     tar -zxvf h2o4gpu_rel-0.4.0.tag.gz &&\
#     cd h2o4gpu &&\
#     R CMD INSTALL src/interface_r &&\
#     rm -rf /usr/local/h2o4gpu

# ----------keras(tensorflow)----------
# r-reticulate virtualenv사용하지 않고 시스템 파이썬 사용
ENV TENSORFLOW_PYTHON=/usr/local/bin/python
RUN Rscript -e "install.packages(c('keras'))"


# ----------arrow----------
# Build dependency 설치
COPY files/libm-2.31.so /lib/x86_64-linux-gnu/
RUN rm /lib/x86_64-linux-gnu/libm.so.6 &&\
    ln -s /lib/x86_64-linux-gnu/libm-2.31.so /lib/x86_64-linux-gnu/libm.so.6
# 환경변수 설정 및 패키지 설치 (inside R)
RUN Rscript -e "Sys.setenv(LIBARROW_BINARY=TRUE); install.packages(c('bit', 'bit64', 'arrow'))"


# ------------set system env and Renviron.site for Rstudio
COPY ./files/hadoop-compilation.sh /etc/profile.d/
COPY ./files/rstudio-entrypoint.sh /usr/local/bin/

# TimeZone (tzdata must be installed)
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#CMD ["/init"]
